version: 0.2

phases:
  pre_build:
    commands:
      - export imageTag=1.0.1
      - export version=1.0.1
      - export imageName=williamhilltest
      - export region=eu-west-1
      - export repoUrl=507965976448.dkr.ecr.eu-west-1.amazonaws.com
      - export fullUrl=$repoUrl/$imageName:$imageTag
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $region)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean install
      - echo "running docker build -t $imageName:$imageTag ."
      - docker build -t $imageName:$imageTag .
      - echo "running docker tag $imageName:$imageTag $fullUrl"
      - docker tag $imageName:$imageTag $fullUrl
      - printf '[{"name":"williamhilltest","imageUri":"%s"}]' $fullUrl > imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $fullUrl
artifacts:
    files: imagedefinitions.json
